version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: storage
      #MYSQL_USER: user
      #MYSQL_PASSWORD: user123
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: flask-app
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root123
      #variável de ambiente que Flask usa para se conectar ao banco de dados
      DB_NAME: storage
